
services:
  dev:
    build:
      context: .
      dockerfile: dockerfile
    container_name: whatsapp-dev
    stdin_open: true
    tty: true
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "8000:8000"
    env_file:
      - ./bot/.env

  bot:
    build:
      context: .
      dockerfile: dockerfile
    container_name: whatsapp-bot
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
      - ./auth_info:/app/auth_info
    env_file:
      - ./bot/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stdin_open: true
    tty: true
